# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build
run-name: ${{ github.actor }} is building the ontoserver website 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4                
    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v4.5.0
      with:
        dockerfile: .
        image-name: ontoserver-website
        tags: latest 0.1
        push-branches: main develop
      env:
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY_URL: ghcr.io/aehrc
        GITHUB_ORGANIZATION: aehrc